// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-campaigns.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var campaigns = [
  {
    id: "CAM-001",
    name: "Summer Movie Festival",
    client: "Cineplex Entertainment",
    campaignType: "Private",
    status: "Active",
    startDate: "2024-06-15",
    endDate: "2024-08-31",
    screens: 45,
    budget: "$25,000",
    orderRegion: "Mumbai"
  },
  {
    id: "CAM-002",
    name: "Horror Night Promo",
    client: "AMC Theatres",
    campaignType: "Private",
    status: "Pending Approval",
    startDate: "2024-10-01",
    endDate: "2024-10-31",
    screens: 32,
    budget: "$18,500",
    orderRegion: "Bangalore"
  },
  {
    id: "CAM-003",
    name: "Holiday Blockbusters",
    client: "Regal Cinemas",
    campaignType: "Private",
    status: "In Review",
    startDate: "2024-11-15",
    endDate: "2024-12-31",
    screens: 67,
    budget: "$42,000",
    orderRegion: "Chennai"
  }
];
var targetGroups = [
  {
    id: "TG-001",
    campaignId: "CAM-001",
    name: "Metro Premium Screens",
    screenCount: 28,
    theatreCount: 9,
    validFrom: "2024-06-15",
    validTill: "2024-08-31",
    updatedBy: "Admin",
    updatedOn: "2024-06-10T10:24:00Z"
  },
  {
    id: "TG-002",
    campaignId: "CAM-001",
    name: "Tier 2 Multiplexes",
    screenCount: 17,
    theatreCount: 6,
    validFrom: "2024-07-01",
    validTill: "2024-08-15",
    updatedBy: "Admin",
    updatedOn: "2024-06-28T08:05:00Z"
  },
  {
    id: "TG-003",
    campaignId: "CAM-003",
    name: "South Region Wide",
    screenCount: 67,
    theatreCount: 21,
    validFrom: "2024-11-15",
    validTill: "2024-12-31",
    updatedBy: "Ops Team",
    updatedOn: "2024-11-02T13:40:00Z"
  }
];
var media = [
  {
    id: "MED-001",
    campaignId: "CAM-001",
    name: "Summer Fest 30s Spot",
    cplName: "SUMMERFEST_TLR-1_F_EN-XX_IN_51_2K",
    cplUuid: "urn:uuid:3f0d1c1a-1111-4a2b-9c3d-77aa2b1c0001",
    contentStatus: "Available",
    durationSeconds: 30,
    updatedBy: "Admin",
    updatedOn: "2024-06-11T09:00:00Z"
  },
  {
    id: "MED-002",
    campaignId: "CAM-002",
    name: "Horror Night Teaser",
    cplName: "HORRORNIGHT_ADV-1_F_EN-XX_IN_20_2K",
    cplUuid: "urn:uuid:3f0d1c1a-2222-4a2b-9c3d-77aa2b1c0002",
    contentStatus: "Missing",
    durationSeconds: 20,
    updatedBy: "Content Team",
    updatedOn: "2024-09-24T15:12:00Z"
  },
  {
    id: "MED-003",
    campaignId: "CAM-003",
    name: "Holiday Slide Pack",
    cplName: "HOLIDAY_SLD-1_F_EN-XX_IN_10_2K",
    cplUuid: "urn:uuid:3f0d1c1a-3333-4a2b-9c3d-77aa2b1c0003",
    contentStatus: "Available",
    durationSeconds: 10,
    updatedBy: "Ops Team",
    updatedOn: "2024-11-05T11:30:00Z"
  }
];

// src/lib/mcp/tools/list-campaigns.ts
var list_campaigns_default = defineTool({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List theatrical ad campaigns in Qube Slate, optionally filtered by status or a text search on campaign name, client, or campaign ID.",
  inputSchema: {
    query: z.string().optional().describe("Text to match against campaign name, client, or campaign ID."),
    status: z.string().optional().describe("Filter by campaign status, e.g. Active, Pending Approval, In Review.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, status }) => {
    const q = query?.trim().toLowerCase();
    const s = status?.trim().toLowerCase();
    const rows = campaigns.filter((c) => {
      const matchesQuery = !q || c.name.toLowerCase().includes(q) || c.client.toLowerCase().includes(q) || c.id.toLowerCase().includes(q);
      const matchesStatus = !s || c.status.toLowerCase() === s;
      return matchesQuery && matchesStatus;
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, campaigns: rows }
    };
  }
});

// src/lib/mcp/tools/get-campaign.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_campaign_default = defineTool2({
  name: "get_campaign",
  title: "Get campaign",
  description: "Get one Qube Slate campaign by ID, including its target groups and media items.",
  inputSchema: {
    campaign_id: z2.string().min(1).describe("Campaign ID, e.g. CAM-001.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ campaign_id }) => {
    const id = campaign_id.trim().toUpperCase();
    const campaign = campaigns.find((c) => c.id.toUpperCase() === id);
    if (!campaign) throw new ToolError(`No campaign found with ID ${campaign_id}`);
    const payload = {
      campaign,
      targetGroups: targetGroups.filter((t) => t.campaignId === campaign.id),
      media: media.filter((m) => m.campaignId === campaign.id)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-target-groups.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_target_groups_default = defineTool3({
  name: "list_target_groups",
  title: "List target groups",
  description: "List target groups (screen selections) in Qube Slate, optionally filtered by campaign ID or a name search.",
  inputSchema: {
    campaign_id: z3.string().optional().describe("Only target groups of this campaign ID."),
    query: z3.string().optional().describe("Text to match against target group name or ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ campaign_id, query }) => {
    const cid = campaign_id?.trim().toUpperCase();
    const q = query?.trim().toLowerCase();
    const rows = targetGroups.filter((t) => {
      const matchesCampaign = !cid || t.campaignId.toUpperCase() === cid;
      const matchesQuery = !q || t.name.toLowerCase().includes(q) || t.id.toLowerCase().includes(q);
      return matchesCampaign && matchesQuery;
    });
    const totals = rows.reduce(
      (acc, t) => ({
        screens: acc.screens + t.screenCount,
        theatres: acc.theatres + t.theatreCount
      }),
      { screens: 0, theatres: 0 }
    );
    return {
      content: [{ type: "text", text: JSON.stringify({ totals, rows }, null, 2) }],
      structuredContent: { count: rows.length, totals, targetGroups: rows }
    };
  }
});

// src/lib/mcp/tools/list-media.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_media_default = defineTool4({
  name: "list_media",
  title: "List media",
  description: "List campaign media (CPLs) in Qube Slate with their content status, optionally filtered by campaign ID, content status, or a text search on media name, CPL name, or CPL UUID.",
  inputSchema: {
    campaign_id: z4.string().optional().describe("Only media of this campaign ID."),
    content_status: z4.string().optional().describe("Filter by content status: Available or Missing."),
    query: z4.string().optional().describe("Text to match against media name, CPL name, or CPL UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ campaign_id, content_status, query }) => {
    const cid = campaign_id?.trim().toUpperCase();
    const status = content_status?.trim().toLowerCase();
    const q = query?.trim().toLowerCase();
    const rows = media.filter((m) => {
      const matchesCampaign = !cid || m.campaignId.toUpperCase() === cid;
      const matchesStatus = !status || m.contentStatus.toLowerCase() === status;
      const matchesQuery = !q || m.name.toLowerCase().includes(q) || m.cplName.toLowerCase().includes(q) || m.cplUuid.toLowerCase().includes(q);
      return matchesCampaign && matchesStatus && matchesQuery;
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, media: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "qube-slate",
  title: "qube-slate",
  version: "0.1.0",
  instructions: "Read-only tools for Qube Slate, a theatrical ad campaign manager. Use `list_campaigns` to browse campaigns, `get_campaign` for one campaign with its target groups and media, `list_target_groups` for screen selections, and `list_media` for campaign CPLs and their content status.",
  tools: [list_campaigns_default, get_campaign_default, list_target_groups_default, list_media_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
